### ISSUE TITLE
Update the ancient protocol desc in our team page.

### ISSUE THREAD

**Issue by avive** [spacemeshos/protocol#21]
https://github.com/orgs/spacemeshos/teams/core-team

**Comment by lrettig** [comment]
Why duplicate this stuff? Why not just point this at https://spacemesh.io/protocol/ or https://spacemesh.io/spacemesh-protocol-v1-0/ or the lightpaper or https://github.com/spacemeshos/protocol?

**Comment by avive** [comment]
done.
