### ISSUE TITLE
Fix relative links

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/protocol#39]
Relative links, e.g., the ones in `mining/01-overview.md`, which point to other md files in the same directory, are broken in the http://protocol.spacemesh.io/#/mining/01-overview doc. Turn these into absolute links.

**Comment by lrettig** [comment]
@avive this is a readability issue for the published docs. Do you know of any way to address this programmatically, or do we need to go in and manually change all the relative links to absolute links?

**Comment by lrettig** [comment]
@avive I know you made a change here, and the internal links are now working, but the sidebar links are not: if you drill down into e.g. the mining section, then click a sidebar link from another section, that doesn't work. What do you think? Do the sidebar links need to be absolute?

**Comment by avive** [comment]
Fixed with move to docusuarus - all links should work in versioned docs as expected.
